### ISSUE TITLE
is it working?

### ISSUE THREAD

**Issue by rlisowski** [dotgee/redmine-foundation-theme#1]
I tried use redmine-foundation-theme as a gem, but it keeps complain about render_menu methods:

``` ruby
ActionView::Template::Error (wrong number of arguments (3 for 1..2)):
    26:             h1
    27:               = link_to Setting.app_title, home_path
    28: 
    29:         = render_menu :top_menu, nil, {class: "left"} if User.current.logged? || !Setting.login_required?
    30: 
    31:         ul.right
    32:           li.has-dropdown.not-click
  lib/redmine/menu_manager.rb:88:in `render_menu'
```

It's seems that app is using core redmine render_menu instead from redmine-foundation-theme.
I tried redmine 2.6.0.
Can you provide more detailed intructions about instalation?

**Comment by almerino** [comment]
Hi korin,

could you check if you have the following line in your application.rb :

``` ruby
config.paths['lib'].unshift(FoundationTheme::Engine.root.join('lib'))
```

I'll try with redmine 2.6.0 and get back to you soon.

**Comment by rlisowski** [comment]
Yes, I had that.
It would be nice if redmine-foundation-theme work with [ThemeChanger](http://www.r-labs.org/projects/r-labs/wiki/Theme_Changer_en)

**Comment by almerino** [comment]
I've got it to work with redmine 2.6-stable.
I did have other problems not related to yours though.

I'll update a fix later for the other issues.

If you could you provide me your application.rb, I'd like to have a look at it.
